### ISSUE TITLE
Test new executable to get rid of java

### ISSUE THREAD

**Issue by theotherp** [hotio/nzbhydra2#19]
I'm currently working on a major update for NZBHydra. If all goes well I will be able to release compiled binaries instead of java libraries, meaning that you don't need to have java installed. Everything you need is in the binary. Apart from the hassle of needing java this also promises some drastic improvements on startup time and memory usage.

One problem I encountered is that the binary is not a "static image" but a "mostly static image", e.g. it needs glibc to run which is why an alpine base image won't work. I've tried the steps described here: https://wiki.alpinelinux.org/wiki/Running_glibc_programs but didn't have any luck. Instead I was able to get it to run using an ubuntu base image and installing libfreetype6.

Apart from that the docker file should mostly look the same. The python wrapper will still be included and just run a binary instead of java. 
Java will still be needed for a while until everybody has successully migrated to the next version because it is called to migrate the database to a new version. Hydra should not run in the root folder but instead `/app` or something like that.

I've made a minimal example here: https://ufile.io/drby73fu Please do not release this as it's just a test version. 

The proposed next steps:

- You test it and see if it works. If you're able to get it to run on alpine or wherever, great.
- I still need some time (to test everything properly and make sure that the new code works as expected. I'm planning to update on the weekend around the 20th.
- I don't know how your pipeline works but hydra version 4.x will be the old way (java) and 5.x will be new one so you could check for that to make the transition work.

Thanks!

**Comment by mrhotio** [comment]
It'll work or completely fail, in which case I'll now know what to do....

**Comment by mrhotio** [comment]
what is the difference between the amd64 and generic release?

**Comment by theotherp** [comment]
amd64 contains a compiled binary and will not require java after all users have migrated from 4.x
The generic release still uses java and can be used by anybody with an unsupported architecture or who can't start the binaries for some other reason.

**Comment by mrhotio** [comment]
You are aware that there's no arm64 release for the latest version?

**Comment by theotherp** [comment]
I am now. Thanks. My build script hasn't matured enough, it seems.
